const ROOM_ACTIONS={
    JOIN:"JOIN_ROOM",
    LEAVE:"LEAVE_ROOM",
    SEND_MESSAGE:"SEND_MESSAGE",
    ON_MESSAGE:"ON_MESSAGE",
    ON_JOIN:"ON_JOIN",
    ON_LEAVE:"ON_LEAVE"
}


export {ROOM_ACTIONS}