const ROOM_ACTIONS={
    JOIN:"JOIN_ROOM",
    LEAVE:"LEAVE_ROOM",
    SEND_MESSAGE:"SEND_MESSAGE",
    ON_MESSAGE:"ON_MESSAGE",
    ON_JOIN:"ON_JOIN",
    ON_LEAVE:"ON_LEAVE",
    SEND_OFFER:"SEND_OFFER",
    RELAY_ICE:"RELAY_ICE",
    SESSION_DESCRIPTION:"SESSION_DESCRIPTION",
    ICE_CANDIDATE:"ICE_CANDIDATE",
    PERMISSON_CONTROL:"PERMISSON_CONTROL",
    ACCEPT_VIDEO_STREAM:"ACCEPT_VIDEO_STREAM",
    CLOSE_CAMERA:"CLOSE_CAMERA",
    ACCEPT_SCREEN_STREAM:".ACCEPT_SCREEN_STREAM"
}


export {ROOM_ACTIONS}