const SET_OFFICE_ROOMS="SET_OFFICE_ROOMS";
const SET_INTERVIEW_ROOMS="SET_INTERVIEW_ROOMS"
const ADD_INTERVIEW_ROOM="ADD_INTERVIEW_ROOM"
const ADD_OFFICE_ROOM="ADD_OFFICE_ROOM"

const TYPES={SET_INTERVIEW_ROOMS,SET_OFFICE_ROOMS,ADD_INTERVIEW_ROOM,ADD_OFFICE_ROOM};

export default TYPES;