const ACTIONS={
   OFFICES_ACTIONS:{
    JOIN:"JOIN_OFFICES_PAGE",
    LEAVE:"LEAVE_OFFICES_PAGE"
   },
   INTERVIEW_ACTIONS:{
    JOIN:"JOIN_INTERVIEWS_PAGE",
    LEAVE:"LEAVE_INTERVIEWS_PAGE"
   }
}

module.exports=ACTIONS;