const ACTIONS={
   OFFICES_ACTIONS:{
    JOIN:"JOIN_OFFICES_PAGE",
    LEAVE:"LEAVE_OFFICES_PAGE"
   },
   INTERVIEW_ACTIONS:{
    JOIN:"JOIN_INTERVIEWS_PAGE",
    LEAVE:"LEAVE_INTERVIEWS_PAGE"
   },
   ROOM_ACTIONS:{
      JOIN:"JOIN_ROOM",
      LEAVE:"LEAVE_ROOM",
      SEND_MESSAGE:"SEND_MESSAGE",
      ON_MESSAGE:"ON_MESSAGE",
      ON_JOIN:"ON_JOIN",
      ON_LEAVE:"ON_LEAVE",
      SEND_OFFER:"SEND_OFFER",
      RELAY_ICE:"RELAY_ICE",
      SESSION_DESCRIPTION:"SESSION_DESCRIPTION",
      PERMISSON_CONTROL:"PERMISSON_CONTROL",
      ACCEPT_VIDEO_STREAM:"ACCEPT_VIDEO_STREAM",
      ICE_CANDIDATE:"ICE_CANDIDATE",
      ACCEPT_SCREEN_STREAM:"ACCEPT_SCREEN_STREAM",
      ACCEPT_MICROPHONE_STREAM:"ACCEPT_MICROPHONE_STREAM"
   }
}

module.exports=ACTIONS;